version: '3'
services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - 3004:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-app:
    build: .
    environment:
      - PORT=3004
    depends_on:
      - redis
      - mongo

  mongo:
    image: mongo
    env_file: ./.env.prod
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db:
