version: '3'
services:
  node-app:
    container_name: node-app
    build: .
    ports:

      - 3004:3004
    restart: always
    volumes:
      - ./:/app:ro
      - /app/node_modules
    # environment:
    #   - PORT=3004
    env_file:
      - ./.env
